import * as React from 'react'

import styles from './Ticker.module.css'
import logo from '../../assets/logo.png'

export default function Ticker() {
  const [ticker, setTicker] = React.useState('')

  React.useEffect(() => {
    window.addEventListener('pywebviewready', function() {
      if (!window.pywebview.state) {
        window.pywebview.state = {}
      }
      // Expose setTicker in order to call it from Python
      window.pywebview.state.setTicker = setTicker
  })
  }, [])

  return (
    <div className={styles.tickerContainer}>
      <h1 className={styles.title}>Welcome to pywebview!</h1>

      <em className={styles.details}>You can freely communicate between Javascript with Python without a HTTP server. This value, for example, is being generated by Python code:</em>
      <strong>{ ticker }</strong>
    </div>
  )
}
