/* global pywebview */

import * as React from 'react';

import './Ticker.scss';
import { useEffect } from 'react';

export default function Ticker() {
  const [ticker, setTicker] = React.useState('---');

  const setupSetTicker = (pywebview: PyWebview) => {
    pywebview.state ||= {};
    // Expose setTicker in order to call it from Python
    pywebview.state.setTicker = setTicker;
  };

  useEffect(() => {
    if (window.pywebview) {
      setupSetTicker(window.pywebview);
    } else {
      window.addEventListener('pywebviewready', () => {
        setupSetTicker(window.pywebview!);
      });
    }
  }, []);

  return (
    <div className="ticker-container">
      <h1>Welcome to pywebview!</h1>

      <em>
        You can freely communicate between Javascript with Python without a HTTP
        server. This value, for example, is being generated by Python code:
      </em>
      <strong>{ticker}</strong>
    </div>
  );
}
